# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d6697761f7642e46fa30eb6df49a99d8fd8b7a7b6f23dba047ec1fcd30c58a55ed73648f5115530b250938fefa6f6fd725bcd52d6653f38d854c38f070aa673

test:
  secret_key_base: e32ed3dc205df56529873d0d06cb56a207931d7c9db588f2d2b3c594255defcdbe29fbf1bcc4696acf615e4cc6a810f6b1e2dde98f3cb7332b758a849b90f878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
